### ISSUE TITLE
Review request - CRS

### ISSUE THREAD

**Issue by LauraRee** [TINF20C/Team_4_Websockets-lwIP#2]
Our CRS is ready for a review.
https://github.com/TINF20C/Team_4_Websockets-lwIP/blob/586dff320e3ea85eb9a5d19b508e1192dd137faf/PROJECT/TINF20C_CRS_lwIP_Team_4_0v1_Eng.docx

**Comment by mrentsch65** [comment]
Access to the documents does not work.

**Comment by BennyGK15** [comment]
New Link:
https://github.com/TINF20C/Team_4_Websockets-lwIP/blob/586dff320e3ea85eb9a5d19b508e1192dd137faf/PROJECT/TINF20C_CRS_lwIP_Team_4_0v1_Eng.docx

**Comment by BennyGK15** [comment]
Reviewed and corrected by @masasume
