### ISSUE TITLE
How to use these "executables"?

### ISSUE THREAD

**Issue by mrentsch65** [TINF20C/Team_4_Websockets-lwIP#8]
Ich habe keine Ahnung, was ich mit diesen Dateien machen kann:

![image](https://user-images.githubusercontent.com/50681355/163755531-09948ee1-b54b-447e-b59d-b8d8a7d06d3e.png)

Bitte beschreiben und als Download im GitHub anlegen, nicht auf einem weiteren Cloudshare.

**Comment by BennyGK15** [comment]
Closed due to inactivity
